const state={apiBase:localStorage.getItem('rs_api_base')||'http://localhost:8000',apiKey:localStorage.getItem('rs_api_key')||'',route:location.hash.replace('#/','')||'dashboard',selected:null};
const NAMES={dashboard:'Command center',opportunities:'Recovery opportunities',simulator:'Decision simulator',evaluation:'Evaluation',audit:'Audit ledger',failures:'Failure lab',settings:'System settings',decision:'Recovery decision'};
const $=selector=>document.querySelector(selector);
const root=$('#view-root');
if (!root) throw new Error('RecoverSense requires #view-root in index.html.');
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function money(n){return n==null||n===''?'—':'₹'+Number(n).toLocaleString('en-IN',{maximumFractionDigits:0})}
function pct(n){return n==null||n===''?'—':Number(n).toFixed(1)+'%'}
function num(n,dp=2){return n==null||n===''?'—':Number(n).toFixed(dp)}
function chip(v){if(v==null||v==='')return`<span class="chip">—</span>`;const s=String(v).toUpperCase();const c=['APPROVE','SCHEDULED','SUCCESS','SUCCESSFUL','RECOVERED','SAFE_TO_RETRY','ACTION_SELECTED','COMPLETED','RECONCILED','PASSED','EXECUTED','SUCCESSFUL_PROVIDER_EXECUTION'].includes(s)?'green':['ESCALATE','DEFER','DEFERRED','AMBIGUOUS','REVIEW','UNALLOCATED','PENDING','DEFERRED_BY_PROVIDER','SUPPORTED_BUT_DELAYED','PROVIDER_PENDING','DEFERRED_MISSING_MANDATE_TOKEN','SKIPPED_STALE_STATE','DEFERRED_PROVIDER_STATE'].includes(s)?'amber':['BLOCK','FAILED','HARD','FAILURE','NEVER_RETRY','DUPLICATE_PREVENTED','TIMEOUT','EXPIRED','POLICY_BLOCKED','FAILED_PROVIDER_EXECUTION','REJECTED_BY_PROVIDER','PROVIDER_ERROR','REJECTED_AMOUNT_LIMIT','REJECTED_INVALID_AMOUNT','REJECTED_MISSING_EMAIL','REJECTED_MISSING_CONTACT','FAILED_PROVIDER_RESPONSE_INVALID','PROVIDER_NOT_CONFIGURED','SAFETY_GATE_BLOCKED'].includes(s)?'red':['SOFT','RETRY_NOW','RETRY_OPTIMAL_WINDOW','SIMULATED_OPERATION','SUPPORTED_REAL_OPERATION','SUPPORTED_REAL_PROVIDER_EXECUTION'].includes(s)?'blue':'';return`<span class="chip ${c}">${esc(v)}</span>`}
function executionModeBanner(exec){const cap=String(exec.capability||'').toUpperCase();const mode=String(exec.execution_mode||'').toLowerCase();let label='';if(mode==='real'){label=(exec.status==='DEFERRED_BY_PROVIDER'||cap==='SUPPORTED_BUT_DELAYED')?'<span class="chip amber">DEFERRED BY PROVIDER</span>':(cap==='SUCCESSFUL_PROVIDER_EXECUTION'?'<span class="chip green">REAL PROVIDER EXECUTION — CAPTURED</span>':'<span class="chip green">REAL PROVIDER EXECUTION</span>')}else if(mode==='simulated'){label='<span class="chip blue">SIMULATED OPERATION — no real provider call</span>'}if(!label)return'';const pending=exec.status==='PROVIDER_PENDING'?' <span class="chip amber">NOT YET CAPTURED — NO RECOVERY CLAIMED</span>':'';const err=exec.provider_error_code?` <span class="chip red">${esc(exec.provider_error_code)}</span>`:'';return`<div class="muted small">Execution mode: ${label}${pending}${err}</div>`}
function field(label,value){return`<div class="field-row"><span class="field-label">${esc(label)}</span><span class="field-value">${value}</span></div>`}
function unavailable(v){return`<span class="state-unavailable">${esc(v)}</span>`}
function metric(label,value,meta,cls=''){return `<div class="card metric"><div class="label">${label}</div><div class="value ${cls}">${value}</div><div class="meta">${meta}</div></div>`}
async function api(path,opts={}){const h={'Content-Type':'application/json',...(state.apiKey?{'X-API-Key':state.apiKey}:{})};const r=await fetch(state.apiBase.replace(/\/$/,'')+path,{...opts,headers:{...h,...(opts.headers||{})}});if(!r.ok){let d=r.statusText;try{const j=await r.json();d=j.detail||JSON.stringify(j)}catch{}throw Error(`${r.status} ${d}`)}return r.json()}
const get=path=>api(path);
const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body)});
function toast(msg,kind='ok'){const e=document.createElement('div');e.className=`toast ${kind}`;e.textContent=msg;$('#toast-root').appendChild(e);setTimeout(()=>e.remove(),4200)}
function go(route){location.hash='#/'+route}
window.addEventListener('hashchange',()=>{state.route=location.hash.replace('#/','')||'dashboard';render()});
const nav=$('#nav');
if(nav)nav.addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(b){go(b.dataset.route);const sidebar=$('#sidebar');if(sidebar)sidebar.classList.remove('open')}});
const mobileMenu=$('#mobile-menu');
if(mobileMenu)mobileMenu.onclick=()=>{const sidebar=$('#sidebar');if(sidebar)sidebar.classList.toggle('open')};
const refreshButton=$('#refresh-btn');
if(refreshButton)refreshButton.onclick=()=>render();
function shell(title){$('#crumb-current').textContent=NAMES[title]||title;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===title))}
function loading(){return`<div class="grid g3"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>`}
async function health(){try{const h=await get('/health');$('#api-dot').className='status-dot ok';$('#api-status').textContent='API connected';$('#mode-label').textContent=(h.mode||'DEMO')+' ENVIRONMENT';const r=await get('/readiness');$('#backend-label').textContent=new URL(state.apiBase).host;const s=await get('/decisions/status');$('#ai-dot').className='status-dot '+(s.active_path==='llm'?'ok':'');$('#ai-status').textContent=s.active_path==='llm'?'AI · live model':'AI · deterministic fallback'}catch{$('#api-dot').className='status-dot err';$('#api-status').textContent='API unreachable';$('#ai-status').textContent='AI unavailable'}}
async function render(){shell(state.route);root.innerHTML=loading();switch(state.route){case'dashboard':return dashboard();case'opportunities':return opportunities();case'simulator':return simulator();case'evaluation':return evaluation();case'audit':return audit();case'failures':return failures();case'settings':return settings();case'decision':return decision(state.selected);default:go('dashboard')}}
async function dashboard(){shell('dashboard');root.innerHTML=`<div class="eyebrow">Operations · live</div><div class="title-row"><div><h1>Command center</h1><p class="subtitle">Real-time view of revenue at risk, recovery decisions, and observed outcomes.</p></div><div class="actions"><button class="btn" id="seed">Generate events</button><button class="btn primary" id="run">Run pending decisions</button></div></div><div class="sp24"></div><div id="metrics" class="grid g4"></div><div class="sp14"></div><div class="card"><div class="section-head"><h2>Recovery pipeline</h2><span>actual decision data</span></div><div id="pipeline"></div></div>`;
  $('#seed').onclick=async()=>{const b=$('#seed');b.disabled=true;b.textContent='Generating…';try{const r=await post('/simulate/events',{n_events:40,seed:Math.floor(Math.random()*99999)});toast(`${r.created} events generated`);await dashboard()}catch(e){toast(e.message,'err');b.disabled=false;b.textContent='Generate events'}};
  $('#run').onclick=async()=>{const b=$('#run');b.disabled=true;b.textContent='Running…';try{const r=await post('/decisions/run-all');toast(`${r.processed} decisions processed`);await dashboard()}catch(e){toast(e.message,'err');b.disabled=false;b.textContent='Run pending decisions'}};
  try{const data=await get('/optimization/portfolio');const items=data.items||[];$('#nav-count').textContent=data.total_opportunities_considered||0;
    const risk=Number(data.total_revenue_at_risk||0),expected=Number(data.expected_recoverable_revenue||0),recovered=Number(data.actual_recovered_revenue||0),allocated=items.filter(i=>i.allocation_status==='ACTION_SELECTED').reduce((s,i)=>s+Number(i.amount_at_risk||0),0);
    $('#metrics').innerHTML=`<div class="card metric"><div class="label">Revenue at risk</div><div class="value">${money(risk)}</div><div class="meta">${items.length} evaluated opportunities</div></div><div class="card metric"><div class="label">Expected recoverable</div><div class="value metric-blue">${money(expected)}</div><div class="meta">probability × amount</div></div><div class="card metric"><div class="label">Recovered revenue</div><div class="value metric-accent">${money(recovered)}</div><div class="meta">recorded outcomes</div></div><div class="card metric"><div class="label">Allocated effort</div><div class="value">${money(allocated)}</div><div class="meta">highest expected-value actions</div></div>`;
    if(!items.length){$('#pipeline').innerHTML='<div class="empty"><strong>No portfolio cycle yet</strong>Generate failed-payment events and run the optimizer.</div>';return}
    $('#pipeline').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Rank</th><th>Payment</th><th>Amount at risk</th><th>Probability</th><th>Expected recovery</th><th>Strategy</th><th>Decision</th><th>Outcome</th></tr></thead><tbody>${items.slice(0,50).map(i=>`<tr onclick="go('decision');state.selected='${esc(i.event_id)}'"><td>${esc(i.rank||'—')}</td><td class="mono">${esc(i.payment_id)}</td><td>${money(i.amount_at_risk)}</td><td>${pct(Number(i.recovery_probability||0)*100)}</td><td>${money(i.expected_recovery)}</td><td>${esc(i.selected_strategy)}</td><td>${chip(i.allocation_status)}</td><td>${chip(i.outcome||'Pending')}</td></tr>`).join('')}</tbody></table></div>`}
  catch(e){$('#metrics').innerHTML=`<div class="card alert error">${esc(e.message)}.</div>`;$('#pipeline').innerHTML=`<div class="alert error">${esc(e.message)}</div>`}}
async function opportunities(){shell('opportunities');root.innerHTML=`<div class="eyebrow">Operations</div><div class="title-row"><div><h1>Recovery opportunities</h1><p class="subtitle">Failed payments where RecoverSense identified a potential recovery action.</p></div></div><div class="sp24"></div><div class="card"><div class="form-grid"><div class="field"><label>Search payment/customer</label><input id="q" placeholder="ID"></div><div class="field"><label>Policy decision</label><select id="pv"><option value="">All</option><option>APPROVE</option><option>ESCALATE</option><option>BLOCK</option><option>DEFER</option></select></div><div class="field"><label>Failure type</label><select id="fc"><option value="">All</option><option>SOFT</option><option>HARD</option><option>AMBIGUOUS</option></select></div></div><div class="sp14"></div><button class="btn primary" id="filter">Apply filters</button></div><div class="sp14"></div><div class="card" style="padding:0"><div class="table-wrap" id="table"><div class="empty">Loading…</div></div></div>`;
  $('#filter').onclick=loadOpportunities;await loadOpportunities();}
async function loadOpportunities(){const table=$('#table');if(!table)return;table.innerHTML='<div class="empty">Loading…</div>';
  try{const q=$('#q').value,pv=$('#pv').value,fc=$('#fc').value;let url='/opportunities?limit=500';if(q)url+=`&q=${encodeURIComponent(q)}`;if(pv)url+=`&policy_verdict=${pv}`;if(fc)url+=`&failure_class=${fc}`;const data=await get(url);const items=data.items||[];$('#nav-count').textContent=data.total||0;
    if(!items.length){table.innerHTML='<div class="empty"><strong>No opportunities</strong>No failed payments match these filters.</div>';return}
    table.innerHTML=`<table class="table"><thead><tr><th>Payment</th><th>Amount</th><th>Failure</th><th>Attempt</th><th>Probability</th><th>Expected recovery</th><th>Strategy</th><th>Policy</th></tr></thead><tbody>${items.map(i=>`<tr onclick="state.selected='${esc(i.event_id)}';go('decision')"><td class="mono">${esc(i.payment_id)}</td><td>${money(i.amount)}</td><td>${chip(i.failure_class)}</td><td>${esc(i.attempt_number)}</td><td>${pct(Number(i.recovery_probability||0)*100)}</td><td>${money(i.expected_net_recovery)}</td><td>${esc(i.selected_strategy||'—')}</td><td>${chip(i.policy_verdict)}</td></tr>`).join('')}</tbody></table>`}
  catch(e){table.innerHTML=`<div class="alert error">${esc(e.message)}</div>`}}
async function decision(id){if(!id){go('opportunities');return}
  shell('decision');root.innerHTML='<div class="empty">Loading decision…</div>';
  try{const data=await get('/opportunities/'+encodeURIComponent(id));
    const e=data.event,dd=data.decision,recovery=dd.recovery||{},ai=dd.ai_recommendation||{},checks=dd.policy_checks||[],exec=dd.execution_result||{},evidence=data.provider_evidence||{};
    const prob=Number(recovery.probability||dd.recovery_probability||0);
    const executed=['SCHEDULED','EXECUTED','INTERNAL_LEDGER_ONLY','UNSUPPORTED_PROVIDER_OPERATION','SAFE_DEFER','DEFERRED_PROVIDER_STATE','SKIPPED_STALE_STATE'].includes(dd.action);
    const hasOutcome=dd.outcome&&dd.outcome!=='null'&&dd.outcome!=='';
    const isRecovered=dd.outcome==='RECOVERED';
    const execBanner=executionModeBanner(exec);
    const tl=[];
    tl.push({label:'Payment failure received',sub:e.failure_reason||'—',state:'done'});
    tl.push({label:'Recovery assessment',sub:`${e.history?e.history.length:0} timing observations`,state:'done'});
    tl.push({label:'Policy evaluated',sub:dd.policy_verdict||'—',state:dd.policy_verdict?'done':'pending'});
    tl.push({label:'Provider state verified',sub:dd.action||'—',state:dd.action?'done':'pending'});
    tl.push({label:'Recovery action',sub:dd.action||'Pending',state:executed||dd.action?'done':'pending'});
    tl.push({label:'Outcome observed',sub:hasOutcome?(isRecovered?`RECOVERED ${money(dd.actual_recovered_amount)}`:dd.outcome):'Waiting for outcome',state:hasOutcome?'done':'pending'});
    tl.push({label:'Audit committed',sub:dd.audit_seq!=null?`seq ${dd.audit_seq}`:'Pending',state:dd.audit_seq!=null?'done':'pending'});
    const drivers=(recovery.drivers||[]).slice(0,4).map(d=>d.label||d);
    root.innerHTML=`<div class="decision">
      <div class="decision-header"><div><div class="eyebrow">Recovery decision</div><h1>${esc(e.payment_id||id)}</h1></div><div class="decision-header-meta"><span class="chip ${dd.policy_verdict==='APPROVE'?'green':dd.policy_verdict==='ESCALATE'||dd.policy_verdict==='DEFER'?'amber':'red'}">${esc(dd.policy_verdict||'PENDING')}</span><button class="btn" onclick="go('opportunities')">Back to queue</button></div></div>
      ${execBanner}<div class="decision-top"><div class="stat"><div class="stat-label">Amount</div><div class="stat-value">${money(e.amount)}</div><div class="stat-sub">${esc(e.failure_reason||'Failed payment')}</div></div><div class="stat"><div class="stat-label">Recovery probability</div><div class="stat-value accent">${pct(prob*100)}</div><div class="stat-sub">${esc(recovery.confidence||'model output')}</div></div><div class="stat"><div class="stat-label">Expected recovery</div><div class="stat-value">${money(dd.expected_recovery)}</div><div class="stat-sub">net ${money(dd.expected_net_recovery)}</div></div><div class="stat"><div class="stat-label">Failure class</div><div class="stat-value">${chip(e.failure_class)}</div><div class="stat-sub">attempt ${esc(e.attempt_number)} / 3</div></div></div>
      <div class="grid g2"><div class="card"><div class="section-head"><h2>Recovery assessment</h2><span>model: ${esc(recovery.model_version||dd.model_version||'—')}</span></div>${field('Failure',esc(e.failure_reason||'—'))}${field('Failure class',chip(e.failure_class))}${field('Timing window',esc(dd.recommended_window||'Unavailable'))}${field('Timing score',dd.timing_score!=null?num(dd.timing_score):'Unavailable')}${field('Customer intent',esc(ai.customer_intent||'Unavailable'))}${field('History points',e.history?e.history.length:'Unavailable')}${drivers.length?`<div class="drivers"><div class="drivers-label">Key drivers</div>${drivers.map(d=>`<span class="driver">${esc(d)}</span>`).join('')}</div>`:''}</div><div class="card"><div class="section-head"><h2>Recommended action</h2><span>${esc(dd.selected_strategy||'—')}</span></div><div class="action-primary">${esc(dd.selected_strategy||'No strategy selected')}</div>${field('Channel',esc(dd.selected_channel||'—'))}${field('Expected gross',money(dd.expected_recovery))}${field('Intervention cost',money(dd.intervention_cost))}${field('NERV',money(dd.nerv))}${field('Policy verdict',chip(dd.policy_verdict))}${field('Execution',chip(dd.action))}${exec.adapter?field('Adapter',esc(exec.adapter)):''}${exec.capability?field('Capability',chip(exec.capability)):''}${exec.provider?field('Provider',esc(exec.provider)):''}${exec.rail?field('Rail',esc(exec.rail)):''}${exec.execution_mode?field('Execution mode',chip(String(exec.execution_mode).toUpperCase())):''}${exec.provider_payment_id?field('Provider payment',`<span class="mono">${esc(exec.provider_payment_id)}</span>`):''}${exec.provider_order_id?field('Provider order',`<span class="mono">${esc(exec.provider_order_id)}</span>`):''}${exec.provider_error_code?field('Provider error code',esc(exec.provider_error_code)):''}${exec.provider_error_reason?field('Provider error reason',esc(exec.provider_error_reason)):''}</div></div>
      ${(dd.alternatives||[]).length?`<div class="card"><div class="section-head"><h2>NERV decision trace</h2><span>channel economics</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Channel</th><th>P(Recovery)</th><th>Recoverable</th><th>Expected Gross</th><th>Cost</th><th>NERV</th><th>Decision</th></tr></thead><tbody>${dd.alternatives.map(c=>`<tr><td>${esc(c.channel||c.strategy)}</td><td>${c.recovery_probability!=null?pct(c.recovery_probability*100):'—'}</td><td>${money(c.recoverable_amount)}</td><td>${money(c.expected_gross_recovery)}</td><td>${money(c.intervention_cost)}</td><td>${money(c.nerv)}</td><td>${esc(c.strategy===dd.selected_strategy?'SELECTED':(c.reason||'REJECTED'))}</td></tr>`).join('')}</tbody></table></div></div>`:''}
      <div class="card"><div class="section-head"><h2>Execution / Provider Evidence</h2><span>${esc(evidence.environment?String(evidence.environment).toUpperCase()+' MODE':'EVENT-LINKED')}</span></div>${field('Provider',esc(evidence.provider||'Unavailable'))}${field('Mandate status',evidence.mandate_status?chip(String(evidence.mandate_status).toUpperCase()):'Unavailable')}${field('Subscription',evidence.subscription_id?`<span class="mono">${esc(evidence.subscription_id)}</span>`:unavailable('Not present in failed event'))}${field('Previous payment',evidence.previous_payment_id?`<span class="mono">${esc(evidence.previous_payment_id)}</span>`:unavailable('No linked payment'))}${field('Provider state',chip(String(evidence.provider_state||'—').toUpperCase()))}${field('Execution rail',evidence.rail?esc(evidence.rail):unavailable('Not executed'))}${field('Mandate token',evidence.mandate_token_verified?'<span class="chip green">VERIFIED ✓</span> Token value hidden for security':unavailable('Not available'))}<p class="evidence-status">Verified provider evidence only — no RecoverSense recovery debit was claimed.</p></div>
      <div class="card"><div class="section-head"><h2>Safety & authorization</h2><span>deterministic policy gate</span></div><div class="checks">${checks.length?checks.map(c=>`<div class="check-row"><span class="check-mark ${c.passed?'pass':'block'}">${c.passed?'✓':'✕'}</span><span class="check-name">${esc(c.name||'Check')}</span><span class="check-detail">${esc(c.detail||'')}</span></div>`).join(''):'<div class="empty">No policy checks reported.</div>'}</div></div>
      <div class="card"><div class="section-head"><h2>Live recovery timeline</h2><span>derived from backend state</span></div><div class="timeline">${tl.map((t,i)=>`<div class="tl-item ${t.state}"><div class="tl-dot">${t.state==='done'?i+1:'•'}</div><div class="tl-content"><div class="tl-label">${esc(t.label)}</div><div class="tl-sub">${esc(t.sub)}</div></div></div>`).join('')}</div></div>
      <div class="grid g2"><div class="card"><div class="section-head"><h2>Outcome</h2><span>expected vs actual</span></div><div class="outcome-grid"><div><div class="outcome-label">Expected recovery</div><div class="outcome-value">${money(dd.expected_recovery)}</div></div><div><div class="outcome-label">Actual recovered</div><div class="outcome-value ${isRecovered?'recovered':''}">${dd.actual_recovered_amount!=null?money(dd.actual_recovered_amount):'—'}</div></div></div><div class="outcome-status">${isRecovered?`<span class="chip green">RECOVERED</span> confirmed outcome`:hasOutcome?`<span class="chip">${esc(dd.outcome)}</span>`:`<span class="chip amber">WAITING FOR OUTCOME</span>`}</div></div><div class="card"><div class="section-head"><h2>Audit</h2><span>tamper-evident</span></div>${field('Sequence',dd.audit_seq!=null?dd.audit_seq:'—')}${field('Hash',dd.audit_hash?`<code class="hash">${esc(String(dd.audit_hash).slice(0,12))}…</code>`:'—')}${field('Model version',esc(dd.model_version||'—'))}${field('Policy version',esc(dd.policy_version||'—'))}</div></div>
    </div>`;
    if(!hasOutcome){setTimeout(()=>{if(state.route==='decision'&&state.selected===id)render()},8000)}
  }
  catch(err){root.innerHTML=`<div class="alert error">Unable to load decision: ${esc(err.message)}</div>`}}
async function simulator(){shell('simulator');root.innerHTML=`<div class="eyebrow">Decision simulator</div><div class="title-row"><div><h1>Pressure-test one payment</h1><p class="subtitle">Change the failure context and watch RecoverSense classify, predict, authorize and execute.</p></div><span class="chip blue">SIMULATION</span></div><div class="sp24"></div><div class="grid g2"><div class="card"><div class="section-head"><h2>Scenario</h2><span>synthetic input</span></div><div class="form-grid"><div class="field"><label>Customer ID</label><input id="s-c" value="cust_demo_001"></div><div class="field"><label>Payment ID</label><input id="s-p" value="pay_demo_001"></div><div class="field"><label>Amount (?)</label><input id="s-a" type="number" value="1499"></div><div class="field"><label>Attempt</label><input id="s-n" type="number" min="1" value="1"></div></div><div class="sp14"></div><div class="field"><label>Failure reason</label><select id="s-f"><option>INSUFFICIENT_FUNDS</option><option>TEMPORARY_PROCESSING_FAILURE</option><option>TRANSIENT_BANK_FAILURE</option><option>MANDATE_REVOKED</option><option>UNKNOWN_FAILURE</option></select></div><div class="sp14"></div><div class="field"><label>Support note</label><textarea id="s-note">Customer confirmed funds will be available this evening.</textarea></div><div class="sp14"></div><button class="btn primary" id="run-sim">Run decision</button></div><div class="card"><div class="section-head"><h2>Result</h2><span>live pipeline</span></div><div id="sim-result"><div class="empty">Run a scenario to see the decision.</div></div></div></div>`;
  $('#run-sim').onclick=runSim;}
async function runSim(){const btn=$('#run-sim');btn.disabled=true;btn.textContent='Running�';
  try{const now=new Date();const iso=now.toISOString().slice(0,19);const payload={event_id:`sim_${now.getTime()}`,customer_id:$('#s-c').value,payment_id:$('#s-p').value||`pay_${now.getTime()}`,subscription_id:`sub_${now.getTime()}`,amount:Number($('#s-a').value)||0,currency:'INR',timestamp:iso,failure_reason:$('#s-f').value,attempt_number:Number($('#s-n').value)||1,mandate_status:'ACTIVE',payment_status:'FAILED',source:'SIMULATOR',mode:'SIMULATION',simulation_id:`sim_${now.getTime()}`,metadata:{support_note:$('#s-note').value,history:[]}};
    const r=await post('/decisions/simulate-one',payload);const opportunity=await get('/opportunities/'+encodeURIComponent(r.event_id));const event=opportunity.event||{},decision=opportunity.decision||{},recovery=decision.recovery||{},execution=decision.execution_result||{},selected=(decision.alternatives||[]).find(c=>c.strategy===decision.selected_strategy)||{};const recommended=decision.selected_strategy||r.ai_context?.recommended_action||'—',probability=recovery.probability??decision.recovery_probability??r.recovery?.recovery_probability,recoverable=selected.recoverable_amount??event.amount,expectedGross=selected.expected_gross_recovery??decision.expected_recovery,interventionCost=selected.intervention_cost??decision.intervention_cost,nerv=selected.nerv??decision.nerv,authorization=decision.policy_verdict??r.policy?.verdict,executionStatus=decision.action??execution.status??r.execution?.status,auditId=decision.audit_seq??r.audit?.seq;
    $('#sim-result').innerHTML=`<div class="result-hero"><div><div class="result-status ${authorization==='APPROVE'?'approve':'block'}">DECISION PROCESSED</div><div class="action-primary">${esc(recommended)}</div><div class="muted small">Event ${esc(r.event_id||'—')}</div></div>${chip(executionStatus)}</div><div class="sp14"></div><div class="grid g2"><div class="card"><div class="section-head"><h2>Recovery economics</h2><span>API result</span></div>${field('Recovery probability',probability!=null?pct(Number(probability)*100):'—')}${field('Recoverable amount',money(recoverable))}${field('Expected gross recovery',money(expectedGross))}${field('Intervention cost',money(interventionCost))}${field('NERV',money(nerv))}</div><div class="card"><div class="section-head"><h2>Authorization & execution</h2><span>deterministic pipeline</span></div>${field('Deterministic authorization',chip(authorization))}${field('Execution status',chip(executionStatus))}${field('Event ID',`<span class="mono">${esc(r.event_id||'—')}</span>`)}${field('Audit ID',auditId!=null?`<span class="mono">${esc(auditId)}</span>`:'—')}<div class="sp14"></div><button class="btn" id="view-opportunity">View in Opportunities</button></div></div>`;
    $('#view-opportunity').onclick=()=>{state.selected=r.event_id;go('decision')};toast('Scenario processed')}
    catch(e){$('#sim-result').innerHTML=`<div class="alert error">${esc(e.message)}</div>`}finally{btn.disabled=false;btn.textContent='Run decision'}}
async function evaluation(){shell('evaluation');root.innerHTML=`<div class="eyebrow">SYNTHETIC CONTROLLED EVALUATION</div><div class="title-row"><div><h1>Evaluation</h1><p class="subtitle">Compare RecoverSense against fixed-timer and population-peak baselines on the same synthetic cohort. This is not live Razorpay production performance.</p></div></div><div class="sp24"></div><div id="eval-status" class="grid g3"></div><div class="sp14"></div><button class="btn primary" id="run-eval">Run evaluation</button><div class="sp14"></div><div id="eval-result"></div>`;
  $('#run-eval').onclick=async()=>{const b=$('#run-eval');b.disabled=true;b.textContent='Evaluating...';try{const r=await post('/evaluation/run',{});renderEval(r);toast('Synthetic evaluation completed')}catch(e){$('#eval-result').innerHTML=`<div class="alert error">${esc(e.message)}</div>`}finally{b.disabled=false;b.textContent='Run evaluation'}};
  try{const r=await get('/evaluation/latest');if(r&&r.recoversense)renderEval(r);else{$('#eval-status').innerHTML='<div class="empty">Run an evaluation to compare strategies.</div>'}}catch{$('#eval-status').innerHTML='<div class="empty">No evaluation available yet.</div>'}}
function renderEval(r){const order=['recoversense','baseline_fixed','baseline_peak_hour'];let html='';order.forEach(k=>{const s=r[k];if(!s)return;html+=`<div class="card metric"><div class="label">${esc((k==='recoversense'?'RecoverSense':k==='baseline_fixed'?'Fixed-timer baseline':'Population-peak baseline'))}</div><div class="value">${money(s.actual_recovered_revenue)}</div><div class="meta">${esc(s.strategy||k)} · ${s.n_events||0} events</div></div>`});$('#eval-status').innerHTML=html||'<div class="empty">No strategy results.</div>';$('#eval-result').innerHTML=`<div class="alert">SYNTHETIC CONTROLLED EVALUATION — held-out benchmark only; not a live Razorpay production result.</div><div class="sp14"></div><div class="table-wrap"><table class="table"><thead><tr><th>Strategy</th><th>Recovered</th><th>Net</th><th>Recovery rate</th><th>Events</th></tr></thead><tbody>${order.map(k=>{const s=r[k];if(!s)return'';return`<tr><td>${esc(s.strategy||k)}</td><td>${money(s.actual_recovered_revenue)}</td><td>${money(s.net_recovered_revenue)}</td><td>${s.recovery_rate_pct!=null?pct(s.recovery_rate_pct):'—'}</td><td>${esc(s.n_events)}</td></tr>`}).join('')}</tbody></table></div>`}
async function audit(){shell('audit');root.innerHTML=`<div class="eyebrow">Trust & evidence</div><div class="title-row"><div><h1>Audit ledger</h1><p class="subtitle">Tamper-evident record of recovery decisions and execution events.</p></div><button class="btn primary" id="verify">Verify chain</button></div><div class="sp24"></div><div id="audit-status"></div><div class="sp14"></div><div class="card"><div class="section-head"><h2>Audit records</h2></div><div id="audit-table"></div></div>`;
  $('#verify').onclick=verifyAudit;await Promise.all([verifyAudit(),loadAuditRecords()]);}
async function loadAuditRecords(){try{const data=await get('/audit?limit=200');const items=data.items||[];if(!items.length){$('#audit-table').innerHTML='<div class="empty"><strong>No audit records</strong>Records will appear after a recovery decision is processed.</div>';return}$('#audit-table').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Time</th><th>Event</th><th>Payment</th><th>Decision</th><th>Action</th><th>Sequence</th><th>Hash</th></tr></thead><tbody>${items.map(item=>`<tr><td class="nowrap">${esc(item.timestamp?new Date(Number(item.timestamp)*1000).toLocaleString():'Not available')}</td><td class="mono">${esc(item.event_id)}</td><td class="mono">${esc(item.payment_id)}</td><td>${chip(item.policy_verdict)}</td><td>${chip(item.action)}</td><td class="mono">${esc(item.seq)}</td><td><details><summary class="hash">${esc(String(item.current_hash||'').slice(0,8))}�${esc(String(item.current_hash||'').slice(-6))}</summary><div class="code"><strong>Previous hash</strong>\n${esc(item.prev_hash||'Not available')}\n\n<strong>Current hash</strong>\n${esc(item.current_hash||'Not available')}</div></details></td></tr>`).join('')}</tbody></table></div>`}catch(error){$('#audit-table').innerHTML=`<div class="alert error">Unable to load audit records: ${esc(error.message)}</div>`}}
async function verifyAudit(){const button=$('#verify'),target=$('#audit-status');if(!button||!target)return;button.disabled=true;button.textContent='Verifying�';target.innerHTML='<div class="empty">Verifying the SHA-256 audit chain�</div>';
  try{const result=await get('/audit/verify');const count=Number(result?.records_verified),first=result?.first_invalid_seq;if(typeof result?.valid!=='boolean'||!Number.isInteger(count)||count<0||!(first===null||Number.isInteger(first)))throw new Error('Backend returned an invalid audit verification response.');if(count===0){target.innerHTML='<div class="alert">No audit records are available to verify.</div>';toast('Audit ledger is empty','err')}else if(result.valid){target.innerHTML=`<div class="result-hero"><div><div class="result-status approve">CHAIN VALID</div><div class="big-prob">${count}</div><div class="muted small">records verified</div></div><span class="chip green">SHA-256 integrity OK</span></div>`;toast(`Chain verified � all ${count} records are valid.`)}else{target.innerHTML=`<div class="result-hero"><div><div class="result-status block">CHAIN BROKEN</div><div class="big-prob">${count}</div><div class="muted small">records verified before failure</div></div><span class="chip red">First invalid sequence: ${esc(first)}</span></div>`;toast('Chain verification failed.','err')}}catch(error){target.innerHTML=`<div class="alert error">Unable to verify audit chain: ${esc(error.message||'Backend unavailable.')}</div>`;toast('Audit verification unavailable.','err')}finally{button.disabled=false;button.textContent='Verify chain'}}
async function failures(){shell('failures');root.innerHTML=`<div class="eyebrow">Failure lab</div><div class="title-row"><div><h1>Break it on purpose.</h1><p class="subtitle">These controls exist only in DEMO_MODE. Each scenario demonstrates a safe failure boundary.</p></div></div><div class="sp24"></div><div class="grid g2">${[['api-timeout','Downstream timeout','Execution timeout is surfaced; no success is assumed.'],['duplicate-webhook','Duplicate webhook','Idempotency prevents a second execution.'],['malformed-llm-output','Malformed AI output','Schema validation rejects unsafe output.'],['policy-rejection','Policy rejection','Retry limit forces deterministic escalation.']].map(x=>`<div class="card"><div class="section-head"><h2>${x[1]}</h2><span>fault injection</span></div><p class="subtitle">${x[2]}</p><div class="sp14"></div><button class="btn" onclick="fault('${x[0]}')">Trigger scenario</button><div class="sp14"></div><div id="fault-${x[0]}" class="code">Waiting�</div></div>`).join('')}</div>`}
window.fault=async s=>{try{const r=await post('/failure-demo/'+s);$('#fault-'+s).textContent=JSON.stringify(r,null,2)}catch(e){$('#fault-'+s).textContent=e.message}}
async function settings(){shell('settings');root.innerHTML=`<div class="eyebrow">Control plane</div><div class="title-row"><div><h1>System settings</h1><p class="subtitle">Configure the frontend connection and inspect the active policy.</p></div></div><div class="sp24"></div><div class="grid g2"><div class="card"><div class="section-head"><h2>Connection</h2><span>local / deployed</span></div><div class="field"><label>Backend URL</label><input id="api-url" value="${esc(state.apiBase)}"></div><div class="sp14"></div><div class="field"><label>API key (optional in demo)</label><input id="api-key" type="password" value="${esc(state.apiKey)}"></div><div class="sp14"></div><button class="btn primary" id="save-settings">Save & reconnect</button></div><div class="card"><div class="section-head"><h2>Policy configuration</h2><span>server-side gate</span></div><div id="policy">Loading�</div></div></div>`;
  $('#save-settings').onclick=()=>{state.apiBase=$('#api-url').value.replace(/\/$/,'');state.apiKey=$('#api-key').value;localStorage.setItem('rs_api_base',state.apiBase);localStorage.setItem('rs_api_key',state.apiKey);toast('Connection settings saved');health();render()};
  try{const p=await get('/policy/config');$('#policy').innerHTML=`<div class="check-list"><div class="check"><b>�</b><span>Max retry attempts: <strong>${p.max_retry_attempts}</strong></span></div><div class="check"><b>�</b><span>Minimum expected net recovery: <strong>${money(p.min_expected_net_recovery)}</strong></span></div><div class="check"><b>�</b><span>Autonomous amount ceiling: <strong>${money(p.max_autonomous_amount)}</strong></span></div><div class="check"><b>�</b><span>Allowed window: <strong>${p.communication_window_start_hour}:00�${p.communication_window_end_hour}:00</strong></span></div></div>`}catch(e){$('#policy').textContent=e.message}}
health();render();setInterval(health,15000);
